server.modules       = ( "mod_indexfile", "mod_dirlisting", "mod_staticfile" )

server.document-root = "/srv/tictactoe"
server.port          = 8888
server.errorlog      = "/dev/stderr"
server.bind          = "0.0.0.0"

index-file.names     = ( "index.html" )

dir-listing.activate = "enable"

mimetype.assign = (
    ".html" => "text/html",
    ".htm"  => "text/html",
    ".css"  => "text/css",
    ".js"   => "application/javascript",
    ".json" => "application/json",
    ".svg"  => "image/svg+xml",
    ".png"  => "image/png",
    ".jpg"  => "image/jpeg",
    ".gif"  => "image/gif",
    ".ico"  => "image/x-icon",
    ".txt"  => "text/plain"
)
